apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs03
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 172.31.127.16
    path: "/mongooseim03"
